name: compose-dev-env-heuristic_ptolemy
services:
  backend:
    build:
      context: C:\Users\ddosn\AppData\Local\Temp\volume-compose-dev-env-heuristic_ptolemy\backend
      dockerfile: Dockerfile
      target: development
    depends_on:
      db:
        condition: service_started
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: compose-dev-env-heuristic_ptolemy
    networks:
      default: null
    secrets:
    - source: db-password
  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    expose:
    - "3306"
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - 127.0.0.1
      - --silent
      interval: 3s
      retries: 5
      start_period: 30s
    image: mariadb
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: compose-dev-env-heuristic_ptolemy
    networks:
      default: null
    restart: always
    secrets:
    - source: db-password
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
      volume: {}
  proxy:
    build:
      context: C:\Users\ddosn\AppData\Local\Temp\volume-compose-dev-env-heuristic_ptolemy\proxy
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: compose-dev-env-heuristic_ptolemy
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: "8080"
      protocol: tcp
networks:
  default:
    name: compose-dev-env-heuristic_ptolemy_default
volumes:
  db-data:
    name: compose-dev-env-heuristic_ptolemy_db-data
secrets:
  db-password:
    name: compose-dev-env-heuristic_ptolemy_db-password
    file: C:\Users\ddosn\AppData\Local\Temp\volume-compose-dev-env-heuristic_ptolemy\db\password.txt
